# Generated by Django 3.1.1 on 2020-10-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All Rounder', 'All Rounder')], default='All Rounder', max_length=20)),
                ('bat_style', models.CharField(choices=[('RHB', 'RHB - Right Handed'), ('LHB', 'LHB - Left Handed')], default='RHB', max_length=20)),
                ('bowl_style', models.CharField(choices=[('RHB', 'RHB - Right Handed'), ('LHB', 'LHB - Left Handed')], default='RHB', max_length=20)),
                ('matches', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('overs', models.FloatField(default=0.0)),
                ('wickets', models.IntegerField(default=0)),
                ('economy', models.FloatField(default=0.0)),
            ],
        ),
    ]
