# Generated by Django 3.1.1 on 2020-10-26 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20201024_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs_per_team', models.IntegerField()),
                ('players_per_team', models.IntegerField()),
                ('toss_won_by', models.CharField(choices=[('team1', 'Team 1'), ('team2', 'Team 2')], default='team1', max_length=10)),
                ('batting_first', models.CharField(choices=[('team1', 'Team 1'), ('team2', 'Team 2')], default='team1', max_length=10)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('result', models.CharField(max_length=30)),
                ('pool_admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
