# Generated by Django 3.1.1 on 2020-10-26 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='overs_per_team',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='players_per_team',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
