# Generated by Django 3.1.2 on 2020-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201026_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByBallStat',
            fields=[
                ('ball_id', models.AutoField(primary_key=True, serialize=False)),
                ('inning', models.IntegerField()),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('strike', models.CharField(max_length=50)),
                ('non_strike', models.CharField(max_length=50)),
                ('bowler', models.CharField(max_length=50)),
                ('is_wide', models.BooleanField(default=False)),
                ('is_no_ball', models.BooleanField(default=False)),
                ('batsman_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(default=None, max_length=50)),
                ('dismissal_kind', models.CharField(choices=[('Bowled', 'Bowled'), ('Caught', 'Caught'), ('Runout', 'Runout')], default=None, max_length=50)),
                ('fielder', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
