# Generated by Django 3.1.2 on 2020-10-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_byballstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='byballstat',
            name='match_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='byballstat',
            name='batsman_runs',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
    ]
