# Generated by Django 3.1.2 on 2020-10-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201031_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byballstat',
            name='match_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.match'),
        ),
    ]
