# Generated by Django 3.1.2 on 2020-11-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201031_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byballstat',
            name='dismissal_kind',
            field=models.CharField(choices=[('Bowled', 'Bowled'), ('Caught', 'Caught'), ('Runout', 'Runout'), ('Stumped', 'Stumped')], default=None, max_length=50),
        ),
    ]
